# Generated by Django 5.2.1 on 2026-03-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='admin_comment',
            field=models.TextField(default='Wait for Admin to Reply'),
        ),
        migrations.AddField(
            model_name='question',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
