# import os
# from pathlib import Path
# import dj_database_url
# # =======================================================================================#


# """
# Django settings for insurance_project project.

# Generated by 'django-admin startproject' using Django 5.2.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# import os
# from pathlib import Path


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-q)y1ns$iop^z#ov+c8_(do(y03#6z(4mqzu0(5#a62et!*lo6n"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# ALLOWED_HOSTS = ['*']


# # Application definition

# INSTALLED_APPS = [
#     #=======================================================================#
#     # "django.contrib.admin",
#     # "django.contrib.auth",
#     # "django.contrib.contenttypes",
#     # "django.contrib.sessions",
#     # "django.contrib.messages",
#     # "django.contrib.staticfiles",
#     # "apps.customer",
#     # "apps.insurance",

#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'apps.customer.apps.CustomerConfig', # Matches apps/customer/
#     'apps.insurance.apps.InsuranceConfig', # Matches apps/insurance/
# ]
# # ==================================================================================================#

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware', # For static files
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware', 
#     'django.contrib.messages.middleware.MessageMiddleware',       
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
#     # "django.middleware.security.SecurityMiddleware",
#     # "django.contrib.sessions.middleware.SessionMiddleware",
#     # "django.middleware.common.CommonMiddleware",
#     # "django.middleware.csrf.CsrfViewMiddleware",
#     # "django.contrib.auth.middleware.AuthenticationMiddleware",
#     # "django.contrib.messages.middleware.MessageMiddleware",
#     # "django.middleware.clickjacking.XFrameOptionsMiddleware",
#     #======================================================================================#
# ]

# ROOT_URLCONF = "insurance_project.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [os.path.join(BASE_DIR, 'templates')],

#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "insurance_project.wsgi.application"


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# #==================================================================================================#
# # DATABASES = {
# #     "default": {
# #         "ENGINE": "django.db.backends.sqlite3",
# #         "NAME": BASE_DIR / "db.sqlite3",
# #     }
# # }

# DATABASES = {
#     'default': dj_database_url.config(
       
#         default=os.environ.get('DATABASE_URL', f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
#         conn_max_age=600
#     )
# }

# # ===================================================================================================#

# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/
# #==================================================================================================#
# # STATIC_URL = '/static/'
# # STATICFILES_DIRS = [BASE_DIR / "static"]
# # MEDIA_URL = '/media/'
# # MEDIA_ROOT = BASE_DIR / 'media'

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'insurance_project', 'static'),
# ]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # This line ensures the graphics are compressed and load fast
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' 

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# #===================================================================================================#

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# LOGIN_URL = '/login/'              # If user tries to access a login-required page, redirect here
# LOGIN_REDIRECT_URL = '/dashboard/' # After successful login, redirect here
# LOGOUT_REDIRECT_URL = '/login/'    # After logout, redirect here
# ==========================================xxxxxx=================================

import os
import dj_database_url
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-q)y1ns$iop^z#ov+c8_(do(y03#6z(4mqzu0(5#a62et!*lo6n"
DEBUG = False
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
   "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.customer",
    "apps.insurance",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.customer.apps.CustomerConfig', # Matches apps/customer/
    'apps.insurance.apps.InsuranceConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "insurance_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "insurance_project.wsgi.application"

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# This path is now relative to manage.py, matching your GitHub structure
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# This is the directory where Render will collect files (Fixes the crash)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# URL Redirect names - updated to match your specific URL patterns
LOGIN_URL = 'adminlogin'
LOGIN_REDIRECT_URL = 'afterlogin'
LOGOUT_REDIRECT_URL = 'home'